### ISSUE TITLE
demo of Autocomplete broken with AT 1.5

### ISSUE THREAD

**Issue by stephane-wis** [ariatemplates-plugins/lightwidgets#6]
Tested Autocomplete on Safari and Chrome (both MacOSX) and the suggestions doesn't open (only a few pixels) in both skins.

**Comment by marclaval** [comment]
Hello,
the full plugin has been updated to AT 1.5.1, this includes the sample available at http://www.ariatemplates.com/plugins/lightwidgets/
I tested it on Mac (both Safari and Chrome) and it was working just fine.

If you still encounter issues with it, please provide more details.
Cheers

**Comment by stephane-wis** [comment]
Hi, there is another problem with the AutoComplete in IE 10 (Windows 7). In the www.ariatemplates.com/plugins/lightwidgets, Autocomplete, type "Air" chose "Air France" click into the text field, click the "X" at the right side. The text "Air France" disappears (as expected). When you click somewhere else (but outside the text field) the "Air France" text appears again in the text field. Weird, isn't it. It happens only with "std" skin. Did I say weird?

**Comment by marclaval** [comment]
Please open another issue for that one as it is different.
In fact, IE10 automatically adds the "X" in input fields, it is not linked to AT 1.5.

We'll have to see if we can/want to handle it, or if we should simply hide it thanks to a specific CSS rule:
http://msdn.microsoft.com/en-us/library/windows/apps/hh465740.aspx
